sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Re23+KcIs+8p6Qex+X1A17bXzA0skb78dDEAofYPKZ/pu1V7IF2FfjFqdU9JetafrEGyebGPwhovIHJoSDaItHxdbYysZI6kBvGIrWhHFGtW7PY8LU+l1jsXSwYKle706PAhN85oo6dOSj84lK7mXCVLfXzWtTO2uCxz4S8IgBQaO2scUBIS2Ep6CSlSTw7IhhxdEKkUzq8XYRI0bMhI62jYdwSMhLKQpWSpk/akvj+lv40r/Xf1pdFkjQamb31UUS/KEZh2p6ZcLAr/2SUd+F2G0RhThzA6RxQPD/n1rQZxODzB98DCAq6whx4+mP8gHZH6ZHBzELQrA/iZkP0hKLJjlRKEadNGjv2LT5cdgqsMXUj37s7CECntPwjdyJn+L7do7rnWHrhmpb7p6xAmZb87tEJbf7996ysDpOjYg1Wa/Za3sw07wN9YAYThI54jRpIxBu28SPbmHFL4Xedp5q+hfUZSTsLVqGNkCIzcFi/j6EKDWmT4aHZilVfDY7f528aPPRYmAeOnjhkSVT/HguwxYJML27HiFSCklqKFCjau5sLpbN/1MI5xOr9npfgPHEVda/eXwIA6WuAxfGOC6J2xdWgfZjl+C5Kq5c/ZddkjYLFR329Fsv9Bcuy7Dd6iJSsCx8etWpNckZXVt8H/RobvHgfyK8xOeIuN0KcfJRY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Just-David_440
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy